language: android

android:
  components:
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - sys-img-x86-android-wear-20
    - android-22

branches:
  except:
    - gh-pages

script:
 - ./gradlew clean check
